"""매매 테이블 추가 trade_signals orders positions trade_history

Revision ID: 03b924eb60d7
Revises: 716800a95e1a
Create Date: 2026-03-30 07:02:09.826506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03b924eb60d7'
down_revision: Union[str, None] = '716800a95e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('signal_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('realized_pnl', sa.Integer(), nullable=False),
    sa.Column('pnl_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('holding_duration_sec', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_reason', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_history_stock_exit', 'trade_history', ['stock_code', 'exit_time'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('unrealized_pnl', sa.Integer(), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('trailing_activated', sa.Boolean(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code')
    )
    op.create_table('trade_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.String(length=10), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_signals_stock_status', 'trade_signals', ['stock_code', 'status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('order_no', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('order_division', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['trade_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_stock', 'orders', ['stock_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_stock', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_trade_signals_stock_status', table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_table('positions')
    op.drop_index('ix_trade_history_stock_exit', table_name='trade_history')
    op.drop_table('trade_history')
    # ### end Alembic commands ###
