"""보조 데이터 테이블 추가 (corp_codes, financial_data, news_sentiments)

Revision ID: 716800a95e1a
Revises: 904367a69982
Create Date: 2026-03-29 22:34:01.924550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '716800a95e1a'
down_revision: Union[str, None] = '904367a69982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('corp_name', sa.String(length=100), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=True),
    sa.Column('modify_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corp_code')
    )
    op.create_index('ix_corp_codes_stock_code', 'corp_codes', ['stock_code'], unique=False)
    op.create_table('financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('operating_profit', sa.BigInteger(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='dart', nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'fiscal_year', 'fiscal_quarter', name='uq_financial_data_stock_year_quarter')
    )
    op.create_index('ix_financial_data_stock_code', 'financial_data', ['stock_code'], unique=False)
    op.create_index('ix_financial_data_year_quarter', 'financial_data', ['fiscal_year', 'fiscal_quarter'], unique=False)
    op.create_table('news_sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('keyword', sa.String(length=100), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_sentiments_stock_published', 'news_sentiments', ['stock_code', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_sentiments_stock_published', table_name='news_sentiments')
    op.drop_table('news_sentiments')
    op.drop_index('ix_financial_data_year_quarter', table_name='financial_data')
    op.drop_index('ix_financial_data_stock_code', table_name='financial_data')
    op.drop_table('financial_data')
    op.drop_index('ix_corp_codes_stock_code', table_name='corp_codes')
    op.drop_table('corp_codes')
    # ### end Alembic commands ###
