"""phase8.5 sprint1 관측성 테이블 3종 추가

Revision ID: a430a1c931b2
Revises: ce7aadd8d078
Create Date: 2026-04-22 04:47:19.010795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a430a1c931b2'
down_revision: Union[str, None] = 'ce7aadd8d078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_metrics_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('bucket', sa.String(length=16), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', 'bucket', name='uq_screening_metrics_date_bucket')
    )
    op.create_index(op.f('ix_screening_metrics_daily_metric_date'), 'screening_metrics_daily', ['metric_date'], unique=False)
    op.create_table('strategy_metrics_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('hour_min_bucket', sa.String(length=8), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', 'stage', 'hour_min_bucket', name='uq_strategy_metrics_date_stage_bucket')
    )
    op.create_index(op.f('ix_strategy_metrics_daily_metric_date'), 'strategy_metrics_daily', ['metric_date'], unique=False)
    op.create_table('virtual_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stock_code', sa.String(length=8), nullable=False),
    sa.Column('stock_name', sa.String(length=64), nullable=True),
    sa.Column('virtual_stage', sa.String(length=64), nullable=False),
    sa.Column('breakout_ref', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Integer(), nullable=True),
    sa.Column('gap_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('prev_close', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('would_execute', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_signals_observed_at'), 'virtual_signals', ['observed_at'], unique=False)
    op.create_index(op.f('ix_virtual_signals_stock_code'), 'virtual_signals', ['stock_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_signals_stock_code'), table_name='virtual_signals')
    op.drop_index(op.f('ix_virtual_signals_observed_at'), table_name='virtual_signals')
    op.drop_table('virtual_signals')
    op.drop_index(op.f('ix_strategy_metrics_daily_metric_date'), table_name='strategy_metrics_daily')
    op.drop_table('strategy_metrics_daily')
    op.drop_index(op.f('ix_screening_metrics_daily_metric_date'), table_name='screening_metrics_daily')
    op.drop_table('screening_metrics_daily')
    # ### end Alembic commands ###
