"""Order signal_json 컬럼 추가

Revision ID: ce7aadd8d078
Revises: 6843d90feee2
Create Date: 2026-04-15 02:09:47.133465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce7aadd8d078'
down_revision: Union[str, None] = '6843d90feee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('signal_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'signal_json')
    # ### end Alembic commands ###
