"""add backtest tables for phase8.6 sprint4

Revision ID: d5d5cc2b391e
Revises: f3b1c4d5e201
Create Date: 2026-05-08 09:57:52.533880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5d5cc2b391e'
down_revision: Union[str, None] = 'f3b1c4d5e201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('n_trading_days', sa.Integer(), nullable=False),
    sa.Column('regime_box_days', sa.Integer(), nullable=False),
    sa.Column('regime_trend_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('ix_backtest_runs_period_end', 'backtest_runs', ['period_end'], unique=False, postgresql_using='btree')
    op.create_table('live_gate_statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('g_bt1_passed', sa.Boolean(), nullable=False),
    sa.Column('g_bt2_passed', sa.Boolean(), nullable=False),
    sa.Column('g_bt3_passed', sa.Boolean(), nullable=False),
    sa.Column('all_passed', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_signal_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('pass_rate_simulated', sa.Float(), nullable=False),
    sa.Column('pass_rate_actual', sa.Float(), nullable=True),
    sa.Column('ks_statistic', sa.Float(), nullable=True),
    sa.Column('ks_pvalue', sa.Float(), nullable=True),
    sa.Column('bootstrap_ci_lower', sa.Float(), nullable=True),
    sa.Column('bootstrap_ci_upper', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_signal_metrics_run_tier', 'backtest_signal_metrics', ['run_id', 'tier'], unique=False)
    op.drop_index(op.f('ix_stocks_is_kospi200'), table_name='stocks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stocks_is_kospi200'), 'stocks', ['is_kospi200'], unique=False)
    op.drop_index('ix_backtest_signal_metrics_run_tier', table_name='backtest_signal_metrics')
    op.drop_table('backtest_signal_metrics')
    op.drop_table('live_gate_statuses')
    op.drop_index('ix_backtest_runs_period_end', table_name='backtest_runs', postgresql_using='btree')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
