"""초기 테이블 생성: settings, stocks, market_data

Revision ID: dd2711851369
Revises: 
Create Date: 2026-03-29 05:35:45.469112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd2711851369'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('market_type', sa.String(length=10), nullable=False),
    sa.Column('stock_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('listed_shares', sa.BigInteger(), nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code')
    )
    op.create_table('market_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('data_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('listed_shares', sa.BigInteger(), nullable=True),
    sa.Column('change_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.stock_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'data_date', 'source')
    )
    op.create_index('ix_market_data_date', 'market_data', ['data_date'], unique=False)
    op.create_index('ix_market_data_stock_date', 'market_data', ['stock_code', 'data_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_data_stock_date', table_name='market_data')
    op.drop_index('ix_market_data_date', table_name='market_data')
    op.drop_table('market_data')
    op.drop_table('stocks')
    op.drop_table('settings')
    # ### end Alembic commands ###
